-- Recreates the Hostel Management core schema in the currently connected Oracle schema.
-- Run only in a fresh/empty schema. Does not insert application data.

SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK


  CREATE TABLE "HOSTEL"
   (	"HOSTEL_ID" NUMBER(5,0),
	"HOSTEL_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"HOSTEL_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"CAPACITY" NUMBER(4,0) NOT NULL ENABLE,
	"LOCATION" VARCHAR2(100),
	 CONSTRAINT "CHK_HOSTEL_TYPE" CHECK (hostel_type IN ('BOYS','GIRLS')) ENABLE,
	 CONSTRAINT "CHK_HOSTEL_CAPACITY" CHECK (capacity > 0) ENABLE,
	 PRIMARY KEY ("HOSTEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_HOSTEL_NAME" UNIQUE ("HOSTEL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "WARDEN"
   (	"WARDEN_ID" NUMBER(5,0),
	"WARDEN_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PHONE" VARCHAR2(15) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100),
	"HOSTEL_ID" NUMBER(5,0) NOT NULL ENABLE,
	 PRIMARY KEY ("WARDEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_WARDEN_PHONE" UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "FK_WARDEN_HOSTEL" FOREIGN KEY ("HOSTEL_ID")
	  REFERENCES "HOSTEL" ("HOSTEL_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "ROOM"
   (	"ROOM_ID" NUMBER(6,0),
	"HOSTEL_ID" NUMBER(5,0) NOT NULL ENABLE,
	"ROOM_NUMBER" VARCHAR2(10) NOT NULL ENABLE,
	"ROOM_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"CAPACITY" NUMBER(2,0) NOT NULL ENABLE,
	"FLOOR_NUMBER" NUMBER(2,0),
	 CONSTRAINT "CHK_ROOM_CAPACITY" CHECK (capacity BETWEEN 1 AND 4) ENABLE,
	 CONSTRAINT "CHK_FLOOR" CHECK (floor_number >= 0) ENABLE,
	 PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_ROOM_HOSTEL_NUMBER" UNIQUE ("HOSTEL_ID", "ROOM_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "CHK_ROOM_TYPE" CHECK (room_type IN ('AC','NON-AC')) ENABLE,
	 CONSTRAINT "FK_ROOM_HOSTEL" FOREIGN KEY ("HOSTEL_ID")
	  REFERENCES "HOSTEL" ("HOSTEL_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "STUDENT"
   (	"STUDENT_ID" NUMBER(10,0),
	"REGISTRATION_NO" VARCHAR2(20) NOT NULL ENABLE,
	"STUDENT_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"GENDER" VARCHAR2(10) NOT NULL ENABLE,
	"DATE_OF_BIRTH" DATE,
	"PHONE" VARCHAR2(15) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE,
	"DEPARTMENT" VARCHAR2(100) NOT NULL ENABLE,
	"YEAR_OF_STUDY" NUMBER(1,0) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(200),
	 CONSTRAINT "CHK_STUDENT_GENDER" CHECK (gender IN ('MALE', 'FEMALE')) ENABLE,
	 CONSTRAINT "CHK_STUDENT_YEAR" CHECK (year_of_study BETWEEN 1 AND 5) ENABLE,
	 PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_STUDENT_REG" UNIQUE ("REGISTRATION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_STUDENT_PHONE" UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_STUDENT_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "ROOM_ALLOCATION"
   (	"ALLOCATION_ID" NUMBER(8,0),
	"STUDENT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ROOM_ID" NUMBER(6,0) NOT NULL ENABLE,
	"ALLOCATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"VACATE_DATE" DATE,
	"STATUS" VARCHAR2(15) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	 CONSTRAINT "CHK_ALLOCATION_STATUS" CHECK (status IN ('ACTIVE', 'VACATED')) ENABLE,
	 CONSTRAINT "CHK_ALLOCATION_DATES" CHECK (vacate_date IS NULL OR vacate_date >= allocation_date) ENABLE,
	 PRIMARY KEY ("ALLOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "FK_ALLOCATION_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE,
	 CONSTRAINT "FK_ALLOCATION_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "ROOM" ("ROOM_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "COMPLAINT"
   (	"COMPLAINT_ID" NUMBER(8,0),
	"STUDENT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"COMPLAINT_TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500) NOT NULL ENABLE,
	"COMPLAINT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE,
	"RESOLUTION" VARCHAR2(500),
	"RESOLVED_DATE" DATE,
	 CONSTRAINT "CHK_COMPLAINT_STATUS" CHECK (status IN ('PENDING', 'IN PROGRESS', 'RESOLVED', 'REJECTED')) ENABLE,
	 CONSTRAINT "CHK_COMPLAINT_TYPE" CHECK (            complaint_type IN (                'ELECTRICAL',                'PLUMBING',                'CLEANING',                'INTERNET',                'ROOM',                'MESS',                'OTHER'            )        ) ENABLE,
	 PRIMARY KEY ("COMPLAINT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "FK_COMPLAINT_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "STUDENT_COMPLAINT"
   (	"COMPLAINT_ID" NUMBER(8,0),
	"ACCUSED_STUDENT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"COMPLAINT_TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500) NOT NULL ENABLE,
	"COMPLAINT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"REPORTED_BY" VARCHAR2(100),
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE,
	"RESOLUTION" VARCHAR2(500),
	"RESOLVED_DATE" DATE,
	"REPORTER_STUDENT_ID" NUMBER(10,0),
	 CONSTRAINT "CHK_SC_STATUS" CHECK (status IN ('PENDING', 'IN PROGRESS', 'RESOLVED', 'DISMISSED')) ENABLE,
	 CONSTRAINT "PK_STUDENT_COMPLAINT" PRIMARY KEY ("COMPLAINT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255  ENABLE,
	 CONSTRAINT "FK_SC_ACCUSED_STUDENT" FOREIGN KEY ("ACCUSED_STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE,
	 CONSTRAINT "FK_SC_REPORTER_STUDENT" FOREIGN KEY ("REPORTER_STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "LEAVE_REQUEST"
   (	"LEAVE_ID" NUMBER(8,0),
	"STUDENT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"FROM_DATE" DATE NOT NULL ENABLE,
	"TO_DATE" DATE NOT NULL ENABLE,
	"REASON" VARCHAR2(500) NOT NULL ENABLE,
	"STATUS" VARCHAR2(15) DEFAULT 'PENDING' NOT NULL ENABLE,
	"APPLIED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"REMARKS" VARCHAR2(500),
	 CONSTRAINT "CHK_LEAVE_DATES" CHECK (to_date >= from_date) ENABLE,
	 CONSTRAINT "CHK_LEAVE_STATUS" CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')) ENABLE,
	 PRIMARY KEY ("LEAVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "FK_LEAVE_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "VISITOR"
   (	"VISITOR_ID" NUMBER(8,0),
	"STUDENT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"VISITOR_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"RELATIONSHIP" VARCHAR2(30),
	"PHONE" VARCHAR2(15),
	"VISIT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"IN_TIME" VARCHAR2(10),
	"OUT_TIME" VARCHAR2(10),
	"PURPOSE" VARCHAR2(200),
	 PRIMARY KEY ("VISITOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "FK_VISITOR_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;


  CREATE TABLE "APP_ACCOUNT"
   (	"ACCOUNT_ID" NUMBER(8,0),
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE,
	"PASSWORD_SALT" VARCHAR2(32) NOT NULL ENABLE,
	"PASSWORD_HASH" VARCHAR2(128) NOT NULL ENABLE,
	"ROLE" VARCHAR2(10) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"STUDENT_ID" NUMBER(10,0),
	"MUST_CHANGE_PASSWORD" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "CHK_APP_ACCOUNT_ACTIVE" CHECK (is_active IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "PK_APP_ACCOUNT" PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "UQ_APP_ACCOUNT_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "CHK_APP_ACCOUNT_ROLE" CHECK (role IN ('ADMIN', 'WARDEN', 'STUDENT')) ENABLE,
	 CONSTRAINT "UQ_APP_ACCOUNT_STUDENT" UNIQUE ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  ENABLE,
	 CONSTRAINT "CHK_APP_ACCOUNT_STUDENT_LINK" CHECK (
        (role = 'STUDENT' AND student_id IS NOT NULL)
        OR (role IN ('ADMIN', 'WARDEN') AND student_id IS NULL)
    ) ENABLE,
	 CONSTRAINT "CHK_APP_ACCOUNT_MUST_CHANGE" CHECK (must_change_password IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "FK_APP_ACCOUNT_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING;

CREATE INDEX idx_sc_accused_student
    ON student_complaint(accused_student_id);

CREATE INDEX idx_sc_reporter_student
    ON student_complaint(reporter_student_id);

