-- Export table DDL for the Hostel Management schema connected in SQL*Plus.
-- This reads metadata only and writes a SQL file in the project sql folder.
-- Run from SQL*Plus after connecting to the schema used by the Node app.

SET DEFINE OFF
SET LONG 2000000
SET LONGCHUNKSIZE 32767
SET PAGESIZE 0
SET LINESIZE 32767
SET TRIMSPOOL ON
SET FEEDBACK OFF
SET HEADING OFF
SET ECHO OFF
SET SERVEROUTPUT ON

BEGIN
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', FALSE);
END;
/

SPOOL C:\Users\Admin\hostel-management\sql\hostel_schema_export.sql

SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
WHERE table_name IN (
    'HOSTEL', 'WARDEN', 'ROOM', 'STUDENT', 'ROOM_ALLOCATION',
    'COMPLAINT', 'STUDENT_COMPLAINT', 'LEAVE_REQUEST', 'VISITOR', 'APP_ACCOUNT'
)
ORDER BY CASE table_name
    WHEN 'HOSTEL' THEN 1
    WHEN 'WARDEN' THEN 2
    WHEN 'ROOM' THEN 3
    WHEN 'STUDENT' THEN 4
    WHEN 'ROOM_ALLOCATION' THEN 5
    WHEN 'COMPLAINT' THEN 6
    WHEN 'STUDENT_COMPLAINT' THEN 7
    WHEN 'LEAVE_REQUEST' THEN 8
    WHEN 'VISITOR' THEN 9
    WHEN 'APP_ACCOUNT' THEN 10
END;

SPOOL OFF
SET FEEDBACK ON
SET HEADING ON

PROMPT Schema DDL exported to C:\Users\Admin\hostel-management\sql\hostel_schema_export.sql
